using System.Collections.Generic;

namespace MobSysFinalsBase1.Shared
{
    public class Country
    {
        public string Name { get; set; }
        public string Code { get; set; } 
        public string DialCode { get; set; } 
    }

    public static class CountryData
    {
        public static List<Country> GetCountries()
        {
            return new List<Country>
            {
                new Country { Name = "Afghanistan", Code = "af", DialCode = "+93" },
                new Country { Name = "Åland Islands", Code = "ax", DialCode = "+358" },
                new Country { Name = "Albania", Code = "al", DialCode = "+355" },
                new Country { Name = "Algeria", Code = "dz", DialCode = "+213" },
                new Country { Name = "American Samoa", Code = "as", DialCode = "+1684" },
                new Country { Name = "Andorra", Code = "ad", DialCode = "+376" },
                new Country { Name = "Angola", Code = "ao", DialCode = "+244" },
                new Country { Name = "Anguilla", Code = "ai", DialCode = "+1264" },
                new Country { Name = "Antarctica", Code = "aq", DialCode = "+672" },
                new Country { Name = "Antigua and Barbuda", Code = "ag", DialCode = "+1268" },
                new Country { Name = "Argentina", Code = "ar", DialCode = "+54" },
                new Country { Name = "Armenia", Code = "am", DialCode = "+374" },
                new Country { Name = "Aruba", Code = "aw", DialCode = "+297" },
                new Country { Name = "Australia", Code = "au", DialCode = "+61" },
                new Country { Name = "Austria", Code = "at", DialCode = "+43" },
                new Country { Name = "Azerbaijan", Code = "az", DialCode = "+994" },
                new Country { Name = "Bahamas", Code = "bs", DialCode = "+1242" },
                new Country { Name = "Bahrain", Code = "bh", DialCode = "+973" },
                new Country { Name = "Bangladesh", Code = "bd", DialCode = "+880" },
                new Country { Name = "Barbados", Code = "bb", DialCode = "+1246" },
                new Country { Name = "Belarus", Code = "by", DialCode = "+375" },
                new Country { Name = "Belgium", Code = "be", DialCode = "+32" },
                new Country { Name = "Belize", Code = "bz", DialCode = "+501" },
                new Country { Name = "Benin", Code = "bj", DialCode = "+229" },
                new Country { Name = "Bermuda", Code = "bm", DialCode = "+1441" },
                new Country { Name = "Bhutan", Code = "bt", DialCode = "+975" },
                new Country { Name = "Bolivia", Code = "bo", DialCode = "+591" },
                new Country { Name = "Bosnia and Herzegovina", Code = "ba", DialCode = "+387" },
                new Country { Name = "Botswana", Code = "bw", DialCode = "+267" },
                new Country { Name = "Bouvet Island", Code = "bv", DialCode = "+47" },
                new Country { Name = "Brazil", Code = "br", DialCode = "+55" },
                new Country { Name = "British Indian Ocean Territory", Code = "io", DialCode = "+246" },
                new Country { Name = "Brunei Darussalam", Code = "bn", DialCode = "+673" },
                new Country { Name = "Bulgaria", Code = "bg", DialCode = "+359" },
                new Country { Name = "Burkina Faso", Code = "bf", DialCode = "+226" },
                new Country { Name = "Burundi", Code = "bi", DialCode = "+257" },
                new Country { Name = "Cambodia", Code = "kh", DialCode = "+855" },
                new Country { Name = "Cameroon", Code = "cm", DialCode = "+237" },
                new Country { Name = "Canada", Code = "ca", DialCode = "+1" },
                new Country { Name = "Cape Verde", Code = "cv", DialCode = "+238" },
                new Country { Name = "Cayman Islands", Code = "ky", DialCode = "+1345" },
                new Country { Name = "Central African Republic", Code = "cf", DialCode = "+236" },
                new Country { Name = "Chad", Code = "td", DialCode = "+235" },
                new Country { Name = "Chile", Code = "cl", DialCode = "+56" },
                new Country { Name = "China", Code = "cn", DialCode = "+86" },
                new Country { Name = "Christmas Island", Code = "cx", DialCode = "+61" },
                new Country { Name = "Cocos (Keeling) Islands", Code = "cc", DialCode = "+61" },
                new Country { Name = "Colombia", Code = "co", DialCode = "+57" },
                new Country { Name = "Comoros", Code = "km", DialCode = "+269" },
                new Country { Name = "Congo", Code = "cg", DialCode = "+242" },
                new Country { Name = "Congo, The Democratic Republic of the Congo", Code = "cd", DialCode = "+243" },
                new Country { Name = "Cook Islands", Code = "ck", DialCode = "+682" },
                new Country { Name = "Costa Rica", Code = "cr", DialCode = "+506" },
                new Country { Name = "Côte d'Ivoire", Code = "ci", DialCode = "+225" },
                new Country { Name = "Croatia", Code = "hr", DialCode = "+385" },
                new Country { Name = "Cuba", Code = "cu", DialCode = "+53" },
                new Country { Name = "Cyprus", Code = "cy", DialCode = "+357" },
                new Country { Name = "Czech Republic", Code = "cz", DialCode = "+420" },
                new Country { Name = "Denmark", Code = "dk", DialCode = "+45" },
                new Country { Name = "Djibouti", Code = "dj", DialCode = "+253" },
                new Country { Name = "Dominica", Code = "dm", DialCode = "+1767" },
                new Country { Name = "Dominican Republic", Code = "do", DialCode = "+1849" },
                new Country { Name = "Ecuador", Code = "ec", DialCode = "+593" },
                new Country { Name = "Egypt", Code = "eg", DialCode = "+20" },
                new Country { Name = "El Salvador", Code = "sv", DialCode = "+503" },
                new Country { Name = "Equatorial Guinea", Code = "gq", DialCode = "+240" },
                new Country { Name = "Eritrea", Code = "er", DialCode = "+291" },
                new Country { Name = "Estonia", Code = "ee", DialCode = "+372" },
                new Country { Name = "Ethiopia", Code = "et", DialCode = "+251" },
                new Country { Name = "Falkland Islands (Malvinas)", Code = "fk", DialCode = "+500" },
                new Country { Name = "Faroe Islands", Code = "fo", DialCode = "+298" },
                new Country { Name = "Fiji", Code = "fj", DialCode = "+679" },
                new Country { Name = "Finland", Code = "fi", DialCode = "+358" },
                new Country { Name = "France", Code = "fr", DialCode = "+33" },
                new Country { Name = "French Guiana", Code = "gf", DialCode = "+594" },
                new Country { Name = "French Polynesia", Code = "pf", DialCode = "+689" },
                new Country { Name = "French Southern Territories", Code = "tf", DialCode = "+262" },
                new Country { Name = "Gabon", Code = "ga", DialCode = "+241" },
                new Country { Name = "Gambia", Code = "gm", DialCode = "+220" },
                new Country { Name = "Georgia", Code = "ge", DialCode = "+995" },
                new Country { Name = "Germany", Code = "de", DialCode = "+49" },
                new Country { Name = "Ghana", Code = "gh", DialCode = "+233" },
                new Country { Name = "Gibraltar", Code = "gi", DialCode = "+350" },
                new Country { Name = "Greece", Code = "gr", DialCode = "+30" },
                new Country { Name = "Greenland", Code = "gl", DialCode = "+299" },
                new Country { Name = "Grenada", Code = "gd", DialCode = "+1473" },
                new Country { Name = "Guadeloupe", Code = "gp", DialCode = "+590" },
                new Country { Name = "Guam", Code = "gu", DialCode = "+1671" },
                new Country { Name = "Guatemala", Code = "gt", DialCode = "+502" },
                new Country { Name = "Guernsey", Code = "gg", DialCode = "+44" },
                new Country { Name = "Guinea", Code = "gn", DialCode = "+224" },
                new Country { Name = "Guinea-Bissau", Code = "gw", DialCode = "+245" },
                new Country { Name = "Guyana", Code = "gy", DialCode = "+592" },
                new Country { Name = "Haiti", Code = "ht", DialCode = "+509" },
                new Country { Name = "Heard Island and Mcdonald Islands", Code = "hm", DialCode = "+672" },
                new Country { Name = "Holy See (Vatican City State)", Code = "va", DialCode = "+379" },
                new Country { Name = "Honduras", Code = "hn", DialCode = "+504" },
                new Country { Name = "Hong Kong", Code = "hk", DialCode = "+852" },
                new Country { Name = "Hungary", Code = "hu", DialCode = "+36" },
                new Country { Name = "Iceland", Code = "is", DialCode = "+354" },
                new Country { Name = "India", Code = "in", DialCode = "+91" },
                new Country { Name = "Indonesia", Code = "id", DialCode = "+62" },
                new Country { Name = "Iran", Code = "ir", DialCode = "+98" },
                new Country { Name = "Iraq", Code = "iq", DialCode = "+964" },
                new Country { Name = "Ireland", Code = "ie", DialCode = "+353" },
                new Country { Name = "Isle of Man", Code = "im", DialCode = "+44" },
                new Country { Name = "Israel", Code = "il", DialCode = "+972" },
                new Country { Name = "Italy", Code = "it", DialCode = "+39" },
                new Country { Name = "Jamaica", Code = "jm", DialCode = "+1876" },
                new Country { Name = "Japan", Code = "jp", DialCode = "+81" },
                new Country { Name = "Jersey", Code = "je", DialCode = "+44" },
                new Country { Name = "Jordan", Code = "jo", DialCode = "+962" },
                new Country { Name = "Kazakhstan", Code = "kz", DialCode = "+7" },
                new Country { Name = "Kenya", Code = "ke", DialCode = "+254" },
                new Country { Name = "Kiribati", Code = "ki", DialCode = "+686" },
                new Country { Name = "Korea, Democratic People's Republic of Korea", Code = "kp", DialCode = "+850" },
                new Country { Name = "Korea, Republic of South Korea", Code = "kr", DialCode = "+82" },
                new Country { Name = "Kosovo", Code = "xk", DialCode = "+383" },
                new Country { Name = "Kuwait", Code = "kw", DialCode = "+965" },
                new Country { Name = "Kyrgyzstan", Code = "kg", DialCode = "+996" },
                new Country { Name = "Laos", Code = "la", DialCode = "+856" },
                new Country { Name = "Latvia", Code = "lv", DialCode = "+371" },
                new Country { Name = "Lebanon", Code = "lb", DialCode = "+961" },
                new Country { Name = "Lesotho", Code = "ls", DialCode = "+266" },
                new Country { Name = "Liberia", Code = "lr", DialCode = "+231" },
                new Country { Name = "Libyan Arab Jamahiriya", Code = "ly", DialCode = "+218" },
                new Country { Name = "Liechtenstein", Code = "li", DialCode = "+423" },
                new Country { Name = "Lithuania", Code = "lt", DialCode = "+370" },
                new Country { Name = "Luxembourg", Code = "lu", DialCode = "+352" },
                new Country { Name = "Macao", Code = "mo", DialCode = "+853" },
                new Country { Name = "Macedonia", Code = "mk", DialCode = "+389" },
                new Country { Name = "Madagascar", Code = "mg", DialCode = "+261" },
                new Country { Name = "Malawi", Code = "mw", DialCode = "+265" },
                new Country { Name = "Malaysia", Code = "my", DialCode = "+60" },
                new Country { Name = "Maldives", Code = "mv", DialCode = "+960" },
                new Country { Name = "Mali", Code = "ml", DialCode = "+223" },
                new Country { Name = "Malta", Code = "mt", DialCode = "+356" },
                new Country { Name = "Marshall Islands", Code = "mh", DialCode = "+692" },
                new Country { Name = "Martinique", Code = "mq", DialCode = "+596" },
                new Country { Name = "Mauritania", Code = "mr", DialCode = "+222" },
                new Country { Name = "Mauritius", Code = "mu", DialCode = "+230" },
                new Country { Name = "Mayotte", Code = "yt", DialCode = "+262" },
                new Country { Name = "Mexico", Code = "mx", DialCode = "+52" },
                new Country { Name = "Micronesia, Federated States of Micronesia", Code = "fm", DialCode = "+691" },
                new Country { Name = "Moldova", Code = "md", DialCode = "+373" },
                new Country { Name = "Monaco", Code = "mc", DialCode = "+377" },
                new Country { Name = "Mongolia", Code = "mn", DialCode = "+976" },
                new Country { Name = "Montenegro", Code = "me", DialCode = "+382" },
                new Country { Name = "Montserrat", Code = "ms", DialCode = "+1664" },
                new Country { Name = "Morocco", Code = "ma", DialCode = "+212" },
                new Country { Name = "Mozambique", Code = "mz", DialCode = "+258" },
                new Country { Name = "Myanmar", Code = "mm", DialCode = "+95" },
                new Country { Name = "Namibia", Code = "na", DialCode = "+264" },
                new Country { Name = "Nauru", Code = "nr", DialCode = "+674" },
                new Country { Name = "Nepal", Code = "np", DialCode = "+977" },
                new Country { Name = "Netherlands", Code = "nl", DialCode = "+31" },
                new Country { Name = "Netherlands Antilles", Code = "an", DialCode = "+599" },
                new Country { Name = "New Caledonia", Code = "nc", DialCode = "+687" },
                new Country { Name = "New Zealand", Code = "nz", DialCode = "+64" },
                new Country { Name = "Nicaragua", Code = "ni", DialCode = "+505" },
                new Country { Name = "Niger", Code = "ne", DialCode = "+227" },
                new Country { Name = "Nigeria", Code = "ng", DialCode = "+234" },
                new Country { Name = "Niue", Code = "nu", DialCode = "+683" },
                new Country { Name = "Norfolk Island", Code = "nf", DialCode = "+672" },
                new Country { Name = "Northern Mariana Islands", Code = "mp", DialCode = "+1670" },
                new Country { Name = "Norway", Code = "no", DialCode = "+47" },
                new Country { Name = "Oman", Code = "om", DialCode = "+968" },
                new Country { Name = "Pakistan", Code = "pk", DialCode = "+92" },
                new Country { Name = "Palau", Code = "pw", DialCode = "+680" },
                new Country { Name = "Palestinian Territory, Occupied", Code = "ps", DialCode = "+970" },
                new Country { Name = "Panama", Code = "pa", DialCode = "+507" },
                new Country { Name = "Papua New Guinea", Code = "pg", DialCode = "+675" },
                new Country { Name = "Paraguay", Code = "py", DialCode = "+595" },
                new Country { Name = "Peru", Code = "pe", DialCode = "+51" },
                new Country { Name = "Philippines", Code = "ph", DialCode = "+63" },
                new Country { Name = "Pitcairn", Code = "pn", DialCode = "+64" },
                new Country { Name = "Poland", Code = "pl", DialCode = "+48" },
                new Country { Name = "Portugal", Code = "pt", DialCode = "+351" },
                new Country { Name = "Puerto Rico", Code = "pr", DialCode = "+1939" },
                new Country { Name = "Qatar", Code = "qa", DialCode = "+974" },
                new Country { Name = "Reunion", Code = "re", DialCode = "+262" },
                new Country { Name = "Romania", Code = "ro", DialCode = "+40" },
                new Country { Name = "Russian Federation", Code = "ru", DialCode = "+7" },
                new Country { Name = "Rwanda", Code = "rw", DialCode = "+250" },
                new Country { Name = "Saint Barthelemy", Code = "bl", DialCode = "+590" },
                new Country { Name = "Saint Helena, Ascension and Tristan Da Cunha", Code = "sh", DialCode = "+290" },
                new Country { Name = "Saint Kitts and Nevis", Code = "kn", DialCode = "+1869" },
                new Country { Name = "Saint Lucia", Code = "lc", DialCode = "+1758" },
                new Country { Name = "Saint Martin", Code = "mf", DialCode = "+590" },
                new Country { Name = "Saint Pierre and Miquelon", Code = "pm", DialCode = "+508" },
                new Country { Name = "Saint Vincent and the Grenadines", Code = "vc", DialCode = "+1784" },
                new Country { Name = "Samoa", Code = "ws", DialCode = "+685" },
                new Country { Name = "San Marino", Code = "sm", DialCode = "+378" },
                new Country { Name = "Sao Tome and Principe", Code = "st", DialCode = "+239" },
                new Country { Name = "Saudi Arabia", Code = "sa", DialCode = "+966" },
                new Country { Name = "Senegal", Code = "sn", DialCode = "+221" },
                new Country { Name = "Serbia", Code = "rs", DialCode = "+381" },
                new Country { Name = "Seychelles", Code = "sc", DialCode = "+248" },
                new Country { Name = "Sierra Leone", Code = "sl", DialCode = "+232" },
                new Country { Name = "Singapore", Code = "sg", DialCode = "+65" },
                new Country { Name = "Slovakia", Code = "sk", DialCode = "+421" },
                new Country { Name = "Slovenia", Code = "si", DialCode = "+386" },
                new Country { Name = "Solomon Islands", Code = "sb", DialCode = "+677" },
                new Country { Name = "Somalia", Code = "so", DialCode = "+252" },
                new Country { Name = "South Africa", Code = "za", DialCode = "+27" },
                new Country { Name = "South Georgia and the South Sandwich Islands", Code = "gs", DialCode = "+500" },
                new Country { Name = "South Sudan", Code = "ss", DialCode = "+211" },
                new Country { Name = "Spain", Code = "es", DialCode = "+34" },
                new Country { Name = "Sri Lanka", Code = "lk", DialCode = "+94" },
                new Country { Name = "Sudan", Code = "sd", DialCode = "+249" },
                new Country { Name = "Suriname", Code = "sr", DialCode = "+597" },
                new Country { Name = "Svalbard and Jan Mayen", Code = "sj", DialCode = "+47" },
                new Country { Name = "Swaziland", Code = "sz", DialCode = "+268" },
                new Country { Name = "Sweden", Code = "se", DialCode = "+46" },
                new Country { Name = "Switzerland", Code = "ch", DialCode = "+41" },
                new Country { Name = "Syrian Arab Republic", Code = "sy", DialCode = "+963" },
                new Country { Name = "Taiwan", Code = "tw", DialCode = "+886" },
                new Country { Name = "Tajikistan", Code = "tj", DialCode = "+992" },
                new Country { Name = "Tanzania, United Republic of Tanzania", Code = "tz", DialCode = "+255" },
                new Country { Name = "Thailand", Code = "th", DialCode = "+66" },
                new Country { Name = "Timor-Leste", Code = "tl", DialCode = "+670" },
                new Country { Name = "Togo", Code = "tg", DialCode = "+228" },
                new Country { Name = "Tokelau", Code = "tk", DialCode = "+690" },
                new Country { Name = "Tonga", Code = "to", DialCode = "+676" },
                new Country { Name = "Trinidad and Tobago", Code = "tt", DialCode = "+1868" },
                new Country { Name = "Tunisia", Code = "tn", DialCode = "+216" },
                new Country { Name = "Turkey", Code = "tr", DialCode = "+90" },
                new Country { Name = "Turkmenistan", Code = "tm", DialCode = "+993" },
                new Country { Name = "Turks and Caicos Islands", Code = "tc", DialCode = "+1649" },
                new Country { Name = "Tuvalu", Code = "tv", DialCode = "+688" },
                new Country { Name = "Uganda", Code = "ug", DialCode = "+256" },
                new Country { Name = "Ukraine", Code = "ua", DialCode = "+380" },
                new Country { Name = "United Arab Emirates", Code = "ae", DialCode = "+971" },
                new Country { Name = "United Kingdom", Code = "gb", DialCode = "+44" },
                new Country { Name = "United States", Code = "us", DialCode = "+1" },
                new Country { Name = "United States Minor Outlying Islands", Code = "um", DialCode = "+1" },
                new Country { Name = "Uruguay", Code = "uy", DialCode = "+598" },
                new Country { Name = "Uzbekistan", Code = "uz", DialCode = "+998" },
                new Country { Name = "Vanuatu", Code = "vu", DialCode = "+678" },
                new Country { Name = "Venezuela, Bolivarian Republic of Venezuela", Code = "ve", DialCode = "+58" },
                new Country { Name = "Vietnam", Code = "vn", DialCode = "+84" },
                new Country { Name = "Virgin Islands, British", Code = "vg", DialCode = "+1284" },
                new Country { Name = "Virgin Islands, U.S.", Code = "vi", DialCode = "+1340" },
                new Country { Name = "Wallis and Futuna", Code = "wf", DialCode = "+681" },
                new Country { Name = "Western Sahara", Code = "eh", DialCode = "+212" },
                new Country { Name = "Yemen", Code = "ye", DialCode = "+967" },
                new Country { Name = "Zambia", Code = "zm", DialCode = "+260" },
                new Country { Name = "Zimbabwe", Code = "zw", DialCode = "+263" }
            };
        }
    }
}